# Generated by Django 6.1 on 2026-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvidadoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do convidado')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('quantidade_esperada', models.PositiveSmallIntegerField(default=1, help_text='Quantas pessoas esse convidado deve trazer (incluindo ele mesmo).', verbose_name='Quantidade esperada')),
                ('grupo', models.CharField(blank=True, help_text='Ex: Família da noiva, Família do noivo, Amigos, Trabalho.', max_length=100, verbose_name='Grupo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('confirmado_manual', models.BooleanField(default=False, help_text='Marque se o convidado confirmou por fora do site (WhatsApp, telefone etc).', verbose_name='Confirmado manualmente pelos noivos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Convidado da lista',
                'verbose_name_plural': 'Lista de convidados',
                'ordering': ['nome'],
            },
        ),
    ]
