# Generated by Django 6.1 on 2026-08-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_noivo', models.CharField(default='Jullio Cesar', max_length=100, verbose_name='Nome do noivo')),
                ('nome_noiva', models.CharField(default='Gabriella', max_length=100, verbose_name='Nome da noiva')),
                ('iniciais', models.CharField(default='JG', max_length=5, verbose_name='Iniciais (monograma)')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora da cerimônia')),
                ('traje', models.CharField(default='Esporte Fino', max_length=100, verbose_name='Traje')),
                ('versiculo_texto', models.TextField(default='Assim, eles já não são dois, mas sim uma só carne. Portanto, o que Deus uniu ninguém separe.', verbose_name='Texto do versículo')),
                ('versiculo_referencia', models.CharField(default='Mateus 19:6', max_length=50, verbose_name='Referência do versículo')),
                ('mensagem_convite', models.TextField(default='Temos a alegria de convidar você para celebrar conosco o dia em que uniremos nossas vidas diante do altar do Senhor, recebendo o Sacramento do Matrimônio.', verbose_name='Texto de abertura do convite')),
                ('mensagem_final', models.TextField(default='Mais do que celebrar um casamento, queremos celebrar a fidelidade de Deus em nossas vidas. A presença de cada pessoa torna este momento ainda mais especial. Obrigado por fazer parte da nossa história.', verbose_name='Mensagem final dos noivos')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, max_length=100, verbose_name='Legenda')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Foto da galeria',
                'verbose_name_plural': 'Fotos da galeria',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text="Deixe em branco para exibir 'Valor Livre'.", max_digits=10, null=True, verbose_name='Valor (R$)')),
                ('icone', models.CharField(default='gift', help_text='Ex: utensils-crossed, plane, refrigerator, table-2, armchair, luggage', max_length=50, verbose_name='Ícone (lucide-icons)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='presentes/', verbose_name='Foto do presente')),
                ('chave_pix', models.CharField(max_length=140, verbose_name='Chave PIX')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para presentear')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Lista de presentes',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('quantidade_convidados', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de convidados')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem para os noivos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Confirmação de presença',
                'verbose_name_plural': 'Confirmações de presença (RSVP)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('data', 'Data'), ('horario', 'Horário'), ('local', 'Local / Endereço'), ('traje', 'Traje'), ('outro', 'Outro')], default='local', max_length=20, verbose_name='Tipo')),
                ('icone', models.CharField(default='map-pin', help_text='Nome de um ícone válido em lucide.dev (ex: calendar-days, clock, map-pin, user)', max_length=50, verbose_name='Ícone (nome do lucide-icons)')),
                ('titulo', models.CharField(help_text='Ex: Local, Data, Horário', max_length=100, verbose_name='Título do card')),
                ('descricao', models.CharField(help_text='Ex: Paróquia São José Operário', max_length=200, verbose_name='Descrição / valor')),
                ('link_maps', models.URLField(blank=True, verbose_name='Link do Google Maps')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='convite.evento')),
            ],
            options={
                'verbose_name': 'Local / Informação da cerimônia',
                'verbose_name_plural': 'Locais / Informações da cerimônia',
                'ordering': ['ordem'],
            },
        ),
    ]
