# Generated by Django 6.1 on 2026-08-11 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_convidado', models.CharField(blank=True, max_length=150, verbose_name='Nome do convidado')),
                ('imagem', models.ImageField(upload_to='fotos_convidados/', verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('aprovada', models.BooleanField(default=False, help_text='Marque para essa foto passar a aparecer na galeria do site.', verbose_name='Aprovada para exibir na galeria pública')),
            ],
            options={
                'verbose_name': 'Foto enviada por convidado',
                'verbose_name_plural': 'Fotos enviadas por convidados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade_pix',
            field=models.CharField(default='BRASIL', help_text='Máximo 15 caracteres. Prefira sem acentos, ex: ANAPOLIS.', max_length=15, verbose_name='Cidade (para o PIX)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_recebedor_pix',
            field=models.CharField(default='NOIVOS', help_text='Máximo 25 caracteres. É o nome que aparece no app do banco de quem for pagar.', max_length=25, verbose_name='Nome do recebedor (para o PIX)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='permitir_fotos_convidados',
            field=models.BooleanField(default=False, help_text='Quando ativado, exibe um botão na seção da cerimônia para os convidados subirem suas próprias fotos do evento.', verbose_name='Permitir que convidados enviem fotos da cerimônia'),
        ),
        migrations.AddField(
            model_name='local',
            name='subtipo_local',
            field=models.CharField(blank=True, choices=[('', '—'), ('cerimonia', 'Cerimônia'), ('recepcao', 'Recepção')], default='', help_text="Preencha só quando Tipo = 'Local / Endereço' e houver mais de um endereço (cerimônia e recepção), para diferenciar os botões 'Ver Localização'.", max_length=20, verbose_name='Subtipo (apenas quando Tipo = Local)'),
        ),
        migrations.CreateModel(
            name='Presenteador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome de quem presenteou')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('presente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenteadores', to='convite.presente')),
            ],
            options={
                'verbose_name': 'Registro de presente',
                'verbose_name_plural': 'Registros de quem presenteou',
                'ordering': ['-criado_em'],
            },
        ),
    ]
